#!/bin/bash

graph=$1
maxLength=$2
plotName=$3

ssh dione "repos/research/*/build/bin/diverse \"resources/$graph\" $maxLength \"$plotName\"" \
    | ssh clear -Y "bash -l -c \"sleep 1; math\""

rsync clear:plot.pdf .
ssh clear "rm plot.pdf"
