#!/bin/bash

graph=$1
flag=$2
constraint=$3
plotName=$4
runs=$5

ssh dione -t "bash -i -c \" \
    cd repos/research/*; \
    hg pull; \
    hg update; \
    make; \
    \""

echo Press [Enter] to disown

ssh dione -t "bash -i -c \" \
    cd repos/research/*; \
    build/bin/diverse $graph $flag $constraint $plotName $runs > $plotName.m & \
    read; \
    disown; \
    \""
