#!/bin/bash

cd $(dirname $0)

output="main"
libs="ompl"
if [ ! -f .no_draw ]
then
    libs="$libs cairo"
else
    defines="-DNO_DRAW"
fi

rm -fR build/{obj,bin}
mkdir -p build/{obj,bin}

link_string=""
for lib in $libs
do
    link_string="$link_string -l$lib"
done

for file in src/*.cpp
do
    objfile=build/obj/$(basename $file).o
    echo Building $file...
    g++ -c $defines -o $objfile -I. $file || exit 1
done

echo Linking with $libs...
g++ -o build/bin/$output build/obj/*.o $link_string

echo Build completed.


